### ISSUE TITLE
Getting error while executing cmake for installation

### ISSUE THREAD

**Issue by sayaz** [guruofquality/gras#120]
Hi,
OS: Ubuntu 14
Gnuradio 3.7.11 was previously installed and I am using it for some time now.

Trying to build and install the gras now. But unable to do the cmake for unix make files. I believe I am following line by line instruction as mentioned.

OS : Ubuntu 14
Gnuradio 3.7.11 was previously installed and I am using it for some time now.

Commands executed:
git clone http://github.com/guruofquality/gras.git
cd gras
git submodule init
git submodule update

mkdir hello
cd hello
cmake /home/ayaz/gras

after executing the last line I am getting the error. "CMakeError.log" and "CMakeOutput.log" is attached.
Please let me know what I did wrong. 

[CMakeError.log](https://github.com/guruofquality/gras/files/2212462/CMakeError.log)
[CMakeOutput.log](https://github.com/guruofquality/gras/files/2212463/CMakeOutput.log)

**Comment by guruofquality** [comment]
Hey I appreciate that you are trying to build the project, and it is seemingly well documented with a nice wiki an all. Years ago a former employer had some pretty bad intentions for me, and I felt that I had to abandon this project due to the intimidation. I was able to start a new project, so whatever brought you to gras you will hopefully find in Pothos: https://github.com/pothosware/PothosCore/wiki Other than that, if you want to fix the build, provide a pull request.
